### ISSUE TITLE
What source card do you use ? Image ?

### ISSUE THREAD

**Issue by maltk2020** [mo3rfan/bpi-m2z-kernel#1]
I do not think it is possible to use your install instructions without knowing what original card you copy the files over.

**Comment by mo3rfan** [comment]
I used the Ubuntu 20.04 image and instructions from here: https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/releases/tag/v3.10 (which was later upgraded to 22.04 LTS with `sudo do-release-upgrade -d` and switched to the newer kernel)

**Comment by maltk2020** [comment]
Super. Thanks very much for your fast and helpful reply.
