### ISSUE TITLE
grep for kernel version fails for me

### ISSUE THREAD

**Issue by maltk2020** [mo3rfan/bpi-m2z-kernel#2]
The command:
  export KV=$(strings ./arch/arm/boot/Image |grep "Linux version"|awk '{print $3}')
  
 gives me KV=5.17.5+ %s
 
 Which I think is incorrect.
 
 This:
   export KV=$(strings ./arch/arm/boot/Image |grep "Linux version 5"|awk '{print $3}')
   
 gets me KV=5.17.5+

**Comment by mo3rfan** [comment]
Thanks, fixed! Limiting to the first grep match may be better:

```
export KV=$(strings ./arch/arm/boot/Image | grep "Linux version" -m 1 | awk '{print $3}')
```

Feel free to send in a pull request next time 😄

**Comment by maltk2020** [comment]
Thanks, and yes, sorry, a pull request would have been better.
